version: '2.1'

services:

  flaskapp:
    build: .
    restart: on-failure
    environment:
      FLASK_LOGLEVEL: INFO

    ports:
      - ${SCRUMBOT_PORT:-5000}:5000
    volumes:
      - ./data:/home/scrumbot/data
      - ./config.yml:/config.yml
