version: '2.1'

services:

  flask_app:
    build: .
    restart: on-failure
    environment:
      FLASK_LOGLEVEL: INFO

    ports:
      - 5000:5000
    volumes:
      - ./data:/home/manager/data
      - ./bot/config.yml:/config.yml
