"""empty message

Revision ID: d37c3d43321c
Revises: d4e1eed1c07e
Create Date: 2018-12-18 08:35:00.487889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37c3d43321c'
down_revision = 'd4e1eed1c07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('state', 'start_time')
    # ### end Alembic commands ###
