"""commute time

Revision ID: d4e1eed1c07e
Revises: e8b1e6584046
Create Date: 2018-12-17 14:11:58.800974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e1eed1c07e'
down_revision = 'e8b1e6584046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commute_time_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('travel_time', sa.Integer(), nullable=True),
    sa.Column('twitter_delay', sa.Integer(), nullable=True),
    sa.Column('maps_prediction', sa.Integer(), nullable=True),
    sa.Column('model_prediction', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commute_time_entry')
    # ### end Alembic commands ###
